<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'logbrowser'  =>  "Logi przeglądarki" , 
   'logbrowser:browse'  =>  "Przeglądaj logi systemowe" , 
   'logbrowser:search'  =>  "Zawęź wyniki" , 
   'logbrowser:user'  =>  "Użytkownik szuka " , 
   'logbrowser:starttime'  =>  "Początkowy czas" , 
   'logbrowser:endtime'  =>  "Końcowy czas" , 
   'logbrowser:explore'  =>  "Przeglądaj logi"
);


add_translation("pl",$polish);



?>