<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'updateclient:label:core'  =>  "Core" , 
   'updateclient:label:plugins'  =>  "Wtyczki" , 
   'updateclient:settings:days'  =>  "Sprawdzaj aktualizacje zawsze" , 
   'updateclient:days'  =>  "dni" , 
   'updateclient:settings:server'  =>  "Aktualizacja serwera" , 
   'updateclient:message:title'  =>  "Wydano nową wersję Elgg!" , 
   'updateclient:message:body'  =>  "Nowa wersja (%s %s) nazwa kodowa \"%s\" została wydana!
		
Pobierz: %s

Przeczytaj informacje o wersji Elgg:

%s"
);


add_translation("pl",$polish);



?>