<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'status'  =>  "Status" , 
   'status:user'  =>  "%s status" , 
   'status:current'  =>  "Aktualny status" , 
   'status:desc'  =>  "Okno statusu pokazuje Twój ostatni status." , 
   'status:posttitle'  =>  "%s status: %s" , 
   'status:everyone'  =>  "Status wszystkich" , 
   'status:strapline'  =>  "%s" , 
   'status:addstatus'  =>  "Ustaw swój status" , 
   'status:messages'  =>  "Status wiadomości" , 
   'status:text'  =>  "Status:" , 
   'status:set'  =>  "ustaw " , 
   'status:clear'  =>  "wyczyść status" , 
   'status:delete'  =>  "usuń status" , 
   'status:nostatus'  =>  "Status nie został ustawiony." , 
   'status:viewhistory'  =>  "zobacz historię" , 
   'item:object:status'  =>  "Status wiadomości" , 
   'status:river:created'  =>  "%s aktualizowany" , 
   'status:river:create'  =>  " status." , 
   'status:posted'  =>  "Twój nowy status został pomyślnie przesłany" , 
   'status:deleted'  =>  "Twój status został usunięty." , 
   'status:blank'  =>  "Sorry: nic nie wpisałeś." , 
   'status:notfound'  =>  "Sorry: Nie można znaleźć określonego statusu wiadomości." , 
   'status:notdeleted'  =>  "Sorry: nie można skasować statusu." , 
   'status:notsaved'  =>  "Coś musiało pójść źle podczas zapisywania, proszę spróbować ponownie lub skontaktować z administratorem." , 
   'status:problem'  =>  "Wystąpił problem. Wygląda na to, że nie można edytować tego statusu."
);


add_translation("pl",$polish);



?>