<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'coppa:text'  =>  "Mam co najmniej 13 lat" , 
   'coppa:fail'  =>  "Musisz mieć co najmniej 13 lat aby się zarejestrować na tej stronie."
);


add_translation("pl",$polish);



?>