<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'translationbrowser'  =>  "Przeglądarka tłumaczeń" , 
   'translationbrowser:save'  =>  "Zapisz"
);


add_translation("pl",$polish);



?>