<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'river:widget:noactivity'  =>  "Nie można znaleźć nikogo aktywnego." , 
   'river:widget:title'  =>  "Aktywny" , 
   'river:widget:description'  =>  "Pokaż twoją ostanią aktywność." , 
   'river:widget:title:friends'  =>  "Aktywni przyjaciele" , 
   'river:widget:description:friends'  =>  "Pokaż co robią twoi przyjaciele." , 
   'river:widget:label:displaynum'  =>  "Liczba wpisów do wyświetlenia:"
);


add_translation("pl",$polish);



?>