<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'openid_server:confirm_trust'  =>  "Tak" , 
   'openid_server:reject_trust'  =>  "Nie" , 
   'openid_server:add_button'  =>  "Dodaj" , 
   'openid_server:delete_option'  =>  "Usuń" , 
   'openid_server:autologin_title'  =>  "Zalogowany"
);


add_translation("pl",$polish);



?>