<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'friends:widget:description'  =>  "Wyświetl kilku z twoich znajomych."
);


add_translation("pl",$polish);



?>