<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'file'  =>  "Pliki" , 
   'files'  =>  "Pliki" , 
   'file:yours'  =>  "Twoje pliki" , 
   'file:yours:friends'  =>  "Pliki twoich znajomych" , 
   'file:user'  =>  "%s' pliki" , 
   'file:friends'  =>  "%s pliki znajomego" , 
   'file:all'  =>  "Wszystkie pliki" , 
   'file:edit'  =>  "Edytuj plik" , 
   'file:more'  =>  "więcej plików" , 
   'file:list'  =>  "zobacz listę" , 
   'file:group'  =>  "Grupa plików" , 
   'file:gallery'  =>  "wyświetl galerie" , 
   'file:gallery_list'  =>  "Widok galerii lub listy" , 
   'file:num_files'  =>  "Liczba plików do wyświetlenia" , 
   'file:upload'  =>  "Dodaj plik" , 
   'file:file'  =>  "Plik" , 
   'file:title'  =>  "Tytuł" , 
   'file:desc'  =>  "Opis" , 
   'file:tags'  =>  "Tagi" , 
   'file:types'  =>  "Typ dodawanych plików" , 
   'file:type:all'  =>  "Wszystkie pliki" , 
   'file:type:video'  =>  "Wideo" , 
   'file:type:document'  =>  "Dokumenty" , 
   'file:type:audio'  =>  "Muzyka" , 
   'file:type:image'  =>  "Zdjęcia" , 
   'file:type:general'  =>  "Ogólne" , 
   'file:user:type:video'  =>  "%s wideo" , 
   'file:user:type:document'  =>  "%s dokumenty" , 
   'file:user:type:audio'  =>  "%s muzyka" , 
   'file:user:type:image'  =>  "%s zdjęcia" , 
   'file:user:type:general'  =>  "%s ogólne pliki" , 
   'file:friends:type:video'  =>  "Wideo twoich znajomych" , 
   'file:friends:type:document'  =>  "Dokumenty twoich znajomych" , 
   'file:friends:type:audio'  =>  "Muzyka twoich znajomych" , 
   'file:friends:type:image'  =>  "Zdjęcia twoich znajomych" , 
   'file:friends:type:general'  =>  "Ogólne pliki twoich znajomych" , 
   'file:widget'  =>  "Plik gadżet" , 
   'file:widget:description'  =>  "Zaprezentuj swoje ostatnie pliki" , 
   'file:download'  =>  "Pobierz" , 
   'file:delete:confirm'  =>  "Czy na pewno chcesz usunąć ten plik?" , 
   'file:tagcloud'  =>  "Chmura tagów" , 
   'file:display:number'  =>  "Liczba plików do wyświetlenia" , 
   'file:river:created'  =>  "%s dodał" , 
   'file:river:item'  =>  "plik" , 
   'file:river:annotate'  =>  "%s skomentował" , 
   'item:object:file'  =>  "Pliki" , 
   'file:saved'  =>  "Twój plik został pomyślnie zapisany." , 
   'file:deleted'  =>  "Plik został usunięty." , 
   'file:none'  =>  "Nie można znaleźć żadnego pliku w tej chwili." , 
   'file:uploadfailed'  =>  "Sorry: nie można zapisać pliku." , 
   'file:downloadfailed'  =>  "Sorry: ten plik nie jest dostępny w tej chwili." , 
   'file:deletefailed'  =>  "Plik nie może być usunięty w tej chwili."
);


add_translation("pl",$polish);



?>