<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'email:validate:subject'  =>  "%s proszę potwierdź swój adres e-mail!" , 
   'email:validate:body'  =>  "Witaj %s,

Proszę potwierdź swój adres e-mail poprzez klikniecie poniższego linku :

%s
" , 
   'email:validate:success:subject'  =>  "Adres e-mail %s potwierdzony!" , 
   'email:validate:success:body'  =>  "Witaj %s,
			
Gratulujemy, twój adres e-mail został pozytywnie zweryfikowany." , 
   'uservalidationbyemail:registerok'  =>  "Aby aktywować swoje konto proszę potwierdź swój adres e-mail poprzez kliknięcie w link który do Ciebie wysłaliśmy."
);


add_translation("pl",$polish);



?>