<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'messageboard:board'  =>  "Tablica ogłoszeń" , 
   'messageboard:messageboard'  =>  "tablica ogłoszeń" , 
   'messageboard:viewall'  =>  "Wyświetl wszystkie" , 
   'messageboard:postit'  =>  "Opublikuj" , 
   'messageboard:history'  =>  "historia" , 
   'messageboard:none'  =>  "Na tym forum nie ma niczego" , 
   'messageboard:num_display'  =>  "Liczba wiadomości do wyświetlenia" , 
   'messageboard:desc'  =>  "To jest wiadomość forum którą możesz umieścić w swoim profilu, gdzie inni użytkownicy mogą zostawić komentarz." , 
   'messageboard:river:annotate'  =>  "%s posiada nową wiadomość." , 
   'messageboard:river:create'  =>  "%s dodano gadżet." , 
   'messageboard:river:update'  =>  "%s aktualizowano wiadomość." , 
   'messageboard:posted'  =>  "Twoja wiadomość została dodana pomyślnie.." , 
   'messageboard:deleted'  =>  "Twoja wiadomość została skasowana." , 
   'messageboard:email:subject'  =>  "Masz nowy komentarz na forum!" , 
   'messageboard:email:body'  =>  "Masz nową wiadomość od %s. Oto ona:

			
%s


Aby wyświetlić wiadmość na forum, kliknij tutaj:

	%s

Aby zobaczyć profil %s, kliknij tutaj:

	%s

Nie możesz odpowiedzieć na ten e-mail." , 
   'messageboard:blank'  =>  "Sorry: musisz coś wpisać przed zapisaniem." , 
   'messageboard:notfound'  =>  "Sorry: Nie można znaleźć określonego przedmiotu." , 
   'messageboard:notdeleted'  =>  "Sorry: nie można skasować tej wiadomości." , 
   'messageboard:failure'  =>  "Wystąpił nieoczekiwany błąd podczas dodawania wiadomości. Proszę spróbować ponownie."
);


add_translation("pl",$polish);



?>