<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'opendd'  =>  "OpenDD" , 
   'opendd:your'  =>  "Twoja aktywność" , 
   'opendd:metadata:key'  =>  "Klucz" , 
   'opendd:metadata:value'  =>  "Wartość" , 
   'opendd:entity:class'  =>  "Klasa" , 
   'opendd:published'  =>  "Opublikowany"
);


add_translation("pl",$polish);



?>