<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'blog'  =>  "Blog" , 
   'blogs'  =>  "Blogi" , 
   'blog:user'  =>  "%s blog" , 
   'blog:user:friends'  =>  "%s przyjaciel blog" , 
   'blog:your'  =>  "Twój blog" , 
   'blog:posttitle'  =>  "%s blog: %s" , 
   'blog:friends'  =>  "Blogi przyjaciół" , 
   'blog:yourfriends'  =>  "Ostatnie blogi twoich przyjaciół" , 
   'blog:everyone'  =>  "Wszystkie blogi" , 
   'blog:read'  =>  "Czytaj bloga" , 
   'blog:addpost'  =>  "Dodaj wpis na bloga" , 
   'blog:editpost'  =>  "Edytuj wpis na blogu" , 
   'blog:text'  =>  "Teksty na blogu" , 
   'blog:strapline'  =>  "%s" , 
   'item:object:blog'  =>  "Wpisy na blogu" , 
   'blog:river:created'  =>  "%s napisał" , 
   'blog:river:updated'  =>  "%s aktualizował" , 
   'blog:river:posted'  =>  "%s wysłał" , 
   'blog:river:create'  =>  "nowy wpis na blogu." , 
   'blog:river:update'  =>  "wpis na blogu." , 
   'blog:river:annotate:create'  =>  "komentarz na blogu." , 
   'blog:posted'  =>  "Twój wpis został pomyślnie dodany." , 
   'blog:deleted'  =>  "Twój wpis został pomyślnie usunięty." , 
   'blog:save:failure'  =>  "Twój wpis nie został zapisany. Spróbuj ponownie." , 
   'blog:blank'  =>  "Sorry: musisz wypełnić wszystkie pola aby dodać wpis." , 
   'blog:notfound'  =>  "Sorry: nie można znaleźć wpisu." , 
   'blog:notdeleted'  =>  "Sorry: nie można skasować wpisu."
);


add_translation("pl",$polish);



?>