<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'apitest'  =>  "API Tester" , 
   'apitest:lastresult'  =>  "Last API Result" , 
   'apitest:apikey'  =>  "Klucz API" , 
   'apitest:secretkey'  =>  "Tajny klucz" , 
   'apitest:endpoint'  =>  "Punkt końcowy" , 
   'apitest:notconfigured'  =>  "API tester nie został skonfigurowany, idź do  Admin -> tools settings" , 
   'apitest:optional'  =>  "Opcjonalny" , 
   'apitest:postdata'  =>  "Dodaj dane POST do zapytania..." , 
   'apitest:execute'  =>  "Wykonaj" , 
   'apitest:execute:nomethod'  =>  "Żadna metoda nie została sprecyzowana." , 
   'apitest:execute:fail'  =>  "Problem z uruchomieniem %s" , 
   'apitest:execute:failwithmessage'  =>  "Problem z uruchomieniem %s, '%s'" , 
   'apitest:execute:success'  =>  "Polecenie uruchomiono pozytywnie"
);


add_translation("pl",$polish);



?>