<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'guidtool'  =>  "Narzędzie GUID" , 
   'guidtool:browse'  =>  "Przeglądaj GUID" , 
   'guidtool:import'  =>  "Import" , 
   'guidtool:import:desc'  =>  "Wklej dane które chcesz zaimportować, muszą być w formacie \"%s\" " , 
   'guidtool:pickformat'  =>  "Proszę wybrać format." , 
   'guidbrowser:export'  =>  "Eksport"
);


add_translation("pl",$polish);



?>