<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'activity:all'  =>  "Aktywność strony" , 
   'activity:your'  =>  "Twoja aktywność" , 
   'activity:friends'  =>  "Twoich przyjaciół aktywność" , 
   'activity:person'  =>  "%s aktywność" , 
   'activity:person:friends'  =>  "%s przyjaciół aktywność" , 
   'activity:usernotfound'  =>  "Użytkownik nie znaleziony" , 
   'activity:nofriendactivity'  =>  "Brak aktywności, może musisz dodać nowych przyjaciół? "
);


add_translation("pl",$polish);



?>