<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'item:object:reported_content'  =>  "Raportowane pozycje" , 
   'reportedcontent'  =>  "Raportowana treść" , 
   'reportedcontent:this'  =>  "Raportuj to" , 
   'reportedcontent:none'  =>  "Nie ma raportowanej treści" , 
   'reportedcontent:report'  =>  "Zgłoś" , 
   'reportedcontent:title'  =>  "Tytuł strony" , 
   'reportedcontent:deleted'  =>  "Raport został skasowany." , 
   'reportedcontent:notdeleted'  =>  "Nie można skasować raportu." , 
   'reportedcontent:delete'  =>  "Usuń" , 
   'reportedcontent:areyousure'  =>  "Czy na pewno chcesz usunąć?" , 
   'reportedcontent:archive'  =>  "Archiwizuj to" , 
   'reportedcontent:archived'  =>  "Raport zarchiwizowany" , 
   'reportedcontent:visit'  =>  "Odwiedź zgłoszoną pozycje" , 
   'reportedcontent:by'  =>  "Zgłoszone przez" , 
   'reportedcontent:objecttitle'  =>  "Tytuł obiektu" , 
   'reportedcontent:objecturl'  =>  "Adres obiektu" , 
   'reportedcontent:reason'  =>  "Powód raportu" , 
   'reportedcontent:description'  =>  "Dlaczego to zgłaszasz?" , 
   'reportedcontent:address'  =>  "Lokalizacja przedmiotu" , 
   'reportedcontent:success'  =>  "Raport został wysłany do administratora witryny" , 
   'reportedcontent:failing'  =>  "Raport nie może zostać wysłany" , 
   'reportedcontent:failed'  =>  "Próba raportowania dla tej treści zakończyła się niepowodzeniem."
);


add_translation("pl",$polish);



?>