<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'feeds'  =>  "Źródło" , 
   'feeds:addfeed'  =>  "Dodaj źródło" , 
   'feeds:title'  =>  "Tytuł" , 
   'feeds:read'  =>  "Twoje źródła" , 
   'feeds:friends'  =>  "Przyjaciół źródła" , 
   'feeds:everyone'  =>  "Strony źródła" , 
   'feeds:url'  =>  "Adres źródła" , 
   'feeds:list'  =>  "Lista źródeł" , 
   'feeds:yourfeeds'  =>  "Twoje źródła" , 
   'feeds:friendsfeeds'  =>  "Przyjaciół źródła" , 
   'feeds:sitefeeds'  =>  "Strony źródła" , 
   'feeds:deleted'  =>  "Usuń źródło" , 
   'feeds:notdeleted'  =>  "Twoje źródło zostało skasowane" , 
   'feeds:nofeeds'  =>  "Brak źródeł do wyświetlenie" , 
   'feeds:allfeeds'  =>  "Wszystkie źródła strony" , 
   'feeds:suredelete'  =>  "Jesteś pewien że chcesz skasować te źródło?" , 
   'feeds:river:created'  =>  "%s dodał widget źródła."
);


add_translation("pl",$polish);



?>