<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'groups'  =>  "Grupy" , 
   'groups:owned'  =>  "Własne grupy" , 
   'groups:yours'  =>  "Twoje grupy" , 
   'groups:user'  =>  "%s grupy" , 
   'groups:all'  =>  "Wszystkie grupy" , 
   'groups:new'  =>  "Utwórz nową grupę" , 
   'groups:edit'  =>  "Edytuj grupę" , 
   'groups:icon'  =>  "Ikona grupy" , 
   'groups:name'  =>  "Nazwa grupy" , 
   'groups:username'  =>  "Krótka nazwa grupy (wyświetlana w adresach URL, tylko litery i cyfry)" , 
   'groups:description'  =>  "Opis" , 
   'groups:briefdescription'  =>  "Krótki opis" , 
   'groups:interests'  =>  "Zainteresowania" , 
   'groups:website'  =>  "Strona www" , 
   'groups:members'  =>  "Członkowie grupy" , 
   'groups:membership'  =>  "Członkostwo" , 
   'groups:access'  =>  "Uprawnienia dostępu" , 
   'groups:owner'  =>  "Właściciel" , 
   'groups:widget:num_display'  =>  "Liczba grup do wyświetlenia" , 
   'groups:widget:membership'  =>  "Członkostwo grupy" , 
   'groups:widgets:description'  =>  "Wyświetl w profilu grupy do których należę" , 
   'groups:noaccess'  =>  "Brak dostępu do grupy" , 
   'groups:cantedit'  =>  "Nie można edytować tej grupy" , 
   'groups:saved'  =>  "Grupa zapisana" , 
   'groups:joinrequest'  =>  "Prośba o członkostwo" , 
   'groups:join'  =>  "Dołącz do grupy" , 
   'groups:leave'  =>  "Odejdź z grupy" , 
   'groups:invite'  =>  "Zaproś przyjaciół" , 
   'groups:inviteto'  =>  "Zaproszeni przyjaciele do '%s'" , 
   'groups:nofriends'  =>  "Nie masz przyjaciół którzy zostali zaproszeni do tej grupy." , 
   'groups:group'  =>  "Grupa" , 
   'item:object:groupforumtopic'  =>  "Tematy forum" , 
   'groups:forum'  =>  "Forum grupy" , 
   'groups:addtopic'  =>  "Dodaj temat" , 
   'groups:forumlatest'  =>  "Ostatnie forum" , 
   'groups:latestdiscussion'  =>  "Ostatnia dyskusja" , 
   'groupspost:success'  =>  "Twój komentarz został pomyślnie dodany" , 
   'groups:alldiscussion'  =>  "Ostatnie dyskusje" , 
   'groups:edittopic'  =>  "Edytuj temat" , 
   'groups:topicmessage'  =>  "Temat wiadomości" , 
   'groups:topicstatus'  =>  "Status tematu" , 
   'groups:reply'  =>  "Dodaj odpowiedź" , 
   'groups:topic'  =>  "Temat" , 
   'groups:posts'  =>  "Posty" , 
   'groups:lastperson'  =>  "Ostatnia osoba" , 
   'groups:when'  =>  "Kiedy" , 
   'grouptopic:notcreated'  =>  "Temat nie został utworzony." , 
   'groups:topicopen'  =>  "Otwarty" , 
   'groups:topicclosed'  =>  "Zamknięty" , 
   'groups:topicresolved'  =>  "Rozwiązany" , 
   'grouptopic:created'  =>  "Twój temat został utworzony." , 
   'groupstopic:deleted'  =>  "Temat skasowany." , 
   'groups:topicsticky'  =>  "Przyklejony" , 
   'groups:topicisclosed'  =>  "Ten temat jest zamknięty." , 
   'groups:topiccloseddesc'  =>  "Ten temat został już zamknięty." , 
   'grouptopic:error'  =>  "Twój temat nie został utworzony. Spróbuj ponownie lub skontaktuj się z administratorem. " , 
   'groups:privategroup'  =>  "Ta grupa jest prywatna, prośba o członkostwo." , 
   'groups:notitle'  =>  "Grupy muszą mieć tytuł" , 
   'groups:cantjoin'  =>  "Nie możesz dołączyć do grupy" , 
   'groups:cantleave'  =>  "Nie możesz odejść z grupy." , 
   'groups:addedtogroup'  =>  "Użytkownik został pomyślnie dodany do tej grupy." , 
   'groups:joinrequestnotmade'  =>  "Dołączenie do grupy nie możliwe." , 
   'groups:joinrequestmade'  =>  "Prośba o dołączenie do grupy pomyślnie wykonana" , 
   'groups:joined'  =>  "Pomyślnie dołączyłeś do grupy!" , 
   'groups:left'  =>  "Pomyślnie opuściłeś grupę" , 
   'groups:notowner'  =>  "Niestety, nie jesteś właścicielem tej grupy." , 
   'groups:alreadymember'  =>  "Jesteś już członkiem tej grupy!" , 
   'groups:userinvited'  =>  "Użytkownik został zaproszony." , 
   'groups:usernotinvited'  =>  "Użytkownik nie został zaproszony." , 
   'groups:invite:subject'  =>  "%s zostałeś zaproszony do %s!" , 
   'groups:invite:body'  =>  "Cześć %s,

Zostałeś zaproszony do '% s' grupy, kliknij przycisk poniżej aby potwierdzić:

%s" , 
   'groups:welcome:subject'  =>  "Witamy w %s !" , 
   'groups:welcome:body'  =>  "Cześć %s!
		
Jesteś już członkiem grupy \"% s\"! Kliknij poniżej aby rozpocząć postowanie!

%s" , 
   'groups:request:subject'  =>  "%s wystąpił z prośbą o dołączenie do %s" , 
   'groups:request:body'  =>  "Cześć %s,

%s wystąpił z wnioskiem o dołączenie do grupy '%s' , kliknij poniżej aby zobaczyć profil:

%s

lub kliknij poniżej aby potwierdzić prośbę:

%s" , 
   'groups:river:member'  =>  "obecnie jest członkiem" , 
   'groups:nowidgets'  =>  "Żaden gadżet nie został zdefiniowany dla tej grupy." , 
   'groups:widgets:members:title'  =>  "Użytkownicy grupy" , 
   'groups:widgets:members:description'  =>  "Lista użytkowników grupy." , 
   'groups:widgets:members:label:displaynum'  =>  "Lista użytkowników grupy." , 
   'groups:widgets:members:label:pleaseedit'  =>  "Proszę skonfigurować ten gadżet." , 
   'groups:widgets:entities:title'  =>  "Obiekty w grupie" , 
   'groups:widgets:entities:description'  =>  "Lista obiektów zapisanych w grupie" , 
   'groups:widgets:entities:label:displaynum'  =>  "Lista obiektów w grupie." , 
   'groups:widgets:entities:label:pleaseedit'  =>  "Proszę skonfigurować ten gadżet." , 
   'groups:forumtopic:edited'  =>  "Temat forum został oprawiony."
);


add_translation("pl",$polish);



?>