<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'siteinfo'  =>  "Informacje o stronie" , 
   'siteinfo:members'  =>  "Użytkownicy strony" , 
   'siteinfo:online'  =>  "Użytkownicy dostępni teraz"
);


add_translation("pl",$polish);



?>