<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'pages'  =>  "Strony" , 
   'pages:yours'  =>  "Twoje strony" , 
   'pages:user'  =>  "Strony domowe" , 
   'pages:group'  =>  "%s strony" , 
   'pages:all'  =>  "Wszystkie strony" , 
   'pages:new'  =>  "Nowa strona" , 
   'pages:groupprofile'  =>  "Strony grupy" , 
   'pages:edit'  =>  "Edytuj tą stronę" , 
   'pages:delete'  =>  "Usuń tą stronę" , 
   'pages:history'  =>  "Historia strony" , 
   'pages:view'  =>  "Zobacz stronę" , 
   'pages:welcome'  =>  "Edytuj wiadomość powitalną" , 
   'pages:welcomeerror'  =>  "Wystąpił problem przy zapisywaniu wiadomości" , 
   'pages:welcomeposted'  =>  "Twoja wiadomość powitalna została zapisana" , 
   'pages:navigation'  =>  "Nawigacja strony" , 
   'item:object:page_top'  =>  "Top-level strony" , 
   'item:object:page'  =>  "Strony" , 
   'item:object:pages_welcome'  =>  "Strony bloków" , 
   'pages:title'  =>  "Tytuł strony" , 
   'pages:description'  =>  "Twoja strona wejściowa" , 
   'pages:tags'  =>  "Tagi" , 
   'pages:access_id'  =>  "Dostęp" , 
   'pages:write_access_id'  =>  "Dostęp do pisania" , 
   'pages:noaccess'  =>  "Brak dostępu do strony" , 
   'pages:cantedit'  =>  "Nie można edytować tej strony" , 
   'pages:saved'  =>  "Strony zapisane" , 
   'pages:notsaved'  =>  "Strona nie może zostać zapisana" , 
   'pages:notitle'  =>  "Musisz podać nazwę dla swojej strony." , 
   'pages:delete:success'  =>  "Twoja strona została pomyślnie usunięta." , 
   'pages:delete:failure'  =>  "Strona nie może zostać skasowana." , 
   'pages:strapline'  =>  "Ostatnia aktualizacja %s przez %s" , 
   'pages:revision'  =>  "Poprawione %s przez %s" , 
   'pages:num'  =>  "Ilość stron do wyświetlenia" , 
   'pages:label:view'  =>  "Zobacz stronę" , 
   'pages:label:edit'  =>  "Edytuj stronę" , 
   'pages:label:history'  =>  "Historia strony" , 
   'pages:sidebar:this'  =>  "Ta strona" , 
   'pages:sidebar:children'  =>  "Podstrony" , 
   'pages:sidebar:parent'  =>  "Źródło" , 
   'pages:newchild'  =>  "Stwórz podstrony" , 
   'pages:backtoparent'  =>  "Wróć do '%s'"
);


add_translation("pl",$polish);



?>