<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'logrotate:period'  =>  "Jak często logi systemowe powinny być archiwizowane?" , 
   'logrotate:weekly'  =>  "Raz na tydzień" , 
   'logrotate:monthly'  =>  "Raz na miesiąc" , 
   'logrotate:yearly'  =>  "Raz na rok" , 
   'logrotate:logrotated'  =>  "Rotacja logów" , 
   'logrotate:lognotrotated'  =>  "Błąd rotacji logów"
);


add_translation("pl",$polish);



?>