<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'bookmarks'  =>  "Zakładki" , 
   'bookmarks:add'  =>  "Zakładka" , 
   'bookmarks:read'  =>  "Lista zakładek" , 
   'bookmarks:friends'  =>  "Przyjaciele - zakładki" , 
   'bookmarks:everyone'  =>  "Wszystkie zakładki na stronie" , 
   'bookmarks:this'  =>  "Zakładka" , 
   'bookmarks:bookmarklet'  =>  "Pobierz bookmarklet" , 
   'bookmarks:inbox'  =>  "Skrzynka odbiorcza zakładek" , 
   'bookmarks:more'  =>  "Więcej zakładek" , 
   'bookmarks:shareditem'  =>  "Bookmarked item" , 
   'bookmarks:with'  =>  "Podziel się z" , 
   'bookmarks:address'  =>  "Adres do zasobu zakładek" , 
   'bookmarks:delete:confirm'  =>  "Czy na pewno chcesz to skasować?" , 
   'bookmarks:shared'  =>  "Zakładka" , 
   'bookmarks:visit'  =>  "Odwiedź zasoby" , 
   'bookmarks:recent'  =>  "Najnowsze zakładki" , 
   'bookmarks:river:created'  =>  "%s zakładka" , 
   'bookmarks:river:annotate'  =>  "%s skomentował" , 
   'bookmarks:river:item'  =>  "an item" , 
   'item:object:bookmarks'  =>  "Stworzone zakładki" , 
   'bookmarks:widget:description'  =>  "Ten gadżet przeznaczony jest dla twojego dashboard'u." , 
   'bookmarks:bookmarklet:description'  =>  "Zakładka pozwala dzielić się ze znajomymi. Aby ją użyć przeciągnij poniższy przycisk do paska swojej przeglądarki:" , 
   'bookmarks:bookmarklet:descriptionie'  =>  "Jeśli korzystasz z programu Internet Explorer, będziesz musiał kliknąć prawym przyciskiem myszy na ikonę bookmarklet, kliknij 'dodaj do ulubionych' " , 
   'bookmarks:bookmarklet:description:conclusion'  =>  "Zapisaną stronę możesz odwiedzić w każdej chwili." , 
   'bookmarks:save:success'  =>  "Twoja zakładka została pomyślnie dodana." , 
   'bookmarks:delete:success'  =>  "Twoja zakładka została pomyślnie skasowany." , 
   'bookmarks:save:failed'  =>  "Twoja zakładka nie może być zapisana. Spróbuj ponownie." , 
   'bookmarks:delete:failed'  =>  "Twoja zakładka nie może być skasowana. Spróbuj ponownie."
);


add_translation("pl",$polish);



?>