<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'apiadmin'  =>  "API administracja" , 
   'apiadmin:keyrevoked'  =>  "Klucz API został unieważniony" , 
   'apiadmin:keynotrevoked'  =>  "Klucz API nie został unieważniony" , 
   'apiadmin:generated'  =>  "Nowa para kluczy API wygenerowana pomyślnie." , 
   'apiadmin:yourref'  =>  "Twoje odniesienie" , 
   'apiadmin:generate'  =>  "Generuj nową parę kluczy" , 
   'apiadmin:noreference'  =>  "Musisz podać odniesienie dla swojego klucza." , 
   'apiadmin:generationfail'  =>  "Problem podczas generowania pary kluczy." , 
   'apiadmin:revoke'  =>  "Unieważnij klucz" , 
   'apiadmin:public'  =>  "Publiczny" , 
   'apiadmin:private'  =>  "Prywatny" , 
   'item:object:api_key'  =>  "Klucze API"
);


add_translation("pl",$polish);



?>