<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'friends:invite'  =>  "Zaproś przyjaciół" , 
   'invitefriends:introduction'  =>  "Aby zaprosić przyjaciół wpisz ich adresy e-mail poniżej (jeden adres w jednej linii):" , 
   'invitefriends:message'  =>  "Wpisz wiadomość jaką mają otrzymać razem z twoim zaproszeniem:" , 
   'invitefriends:subject'  =>  "Zaproszenie do dołączenia %s" , 
   'invitefriends:success'  =>  "Twoi przyjaciele zostali zaproszeni." , 
   'invitefriends:failure'  =>  "Twoi przyjaciele nie zostali zaproszeni." , 
   'invitefriends:message:default'  =>  "Witaj!

Chciałbym Cię serdecznie zaprosić do mojej społeczności %s." , 
   'invitefriends:email'  =>  "Zostałeś zaproszony do społeczności  %s przez %s. Zaproszenie zawiera wiadomość od nadawcy:

%s

Aby dołączyć kliknij w link poniżej:

	%s

Automatycznie dodasz adresata jako przyjaciela gdy utworzysz konto."
);


add_translation("pl",$polish);



?>