<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'messages'  =>  "Wiadomości" , 
   'messages:back'  =>  "powróć do wiadomości" , 
   'messages:user'  =>  "Skrzynka odbiorcza" , 
   'messages:sentMessages'  =>  "Wysłane wiadomości" , 
   'messages:posttitle'  =>  "%s wiadomości: %s" , 
   'messages:inbox'  =>  "Skrzynka odbiorcza" , 
   'messages:send'  =>  "Wyślij wiadomość" , 
   'messages:sent'  =>  "Wysłane wiadomości" , 
   'messages:message'  =>  "Wiadomość" , 
   'messages:title'  =>  "Tytuł" , 
   'messages:to'  =>  "Do" , 
   'messages:from'  =>  "Nadawca" , 
   'messages:fly'  =>  "Let it fly" , 
   'messages:replying'  =>  "Odpowiedz na wiadomość" , 
   'messages:sendmessage'  =>  "Wyślij wiadomość" , 
   'messages:compose'  =>  "Wyślij wiadomość" , 
   'messages:sentmessages'  =>  "Wysłane wiadomości" , 
   'messages:recent'  =>  "Najnowsze wiadomości" , 
   'messages:original'  =>  "Oryginalna wiadomość" , 
   'messages:yours'  =>  "Twoja wiadomość" , 
   'messages:answer'  =>  "Odpowiedz" , 
   'item:object:messages'  =>  "Wiadomości" , 
   'messages:posted'  =>  "Twoja wiadomość została wysłana." , 
   'messages:deleted'  =>  "Twoja wiadomość została pomyślnie usunięta." , 
   'messages:email:subject'  =>  "Masz nową wiadomość!" , 
   'messages:email:body'  =>  "Masz nową wiadomość od %s. Oto ona:

			
%s


Aby zobaczyć wiadomość, kliknij tutaj:

	%s

Aby wysłać wiadomość do %s, kliknij tutaj:

	%s

Nie możesz odpowiedzieć na tę wiadomość." , 
   'messages:blank'  =>  "Musisz coś wpisać zanim zapiszesz." , 
   'messages:notfound'  =>  "Nie można znaleźć określonej wiadomości." , 
   'messages:notdeleted'  =>  "Nie można usunąć tej wiadomości." , 
   'messages:nopermission'  =>  "Nie masz uprawnień, aby usunąć wiadomość." , 
   'messages:nomessages'  =>  "Nie ma żadnych wiadomości, aby wyświetlić." , 
   'messages:user:nonexist'  =>  "Nie można odnaleźć adresata w bazie danych użytkownika."
);


add_translation("pl",$polish);



?>