<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$polish = array( 
   'diagnostics'  =>  "Diagnostyka systemu" , 
   'diagnostics:description'  =>  "Poniższy raport jest przydatny do diagonozowania wszelkich problemów z systemem." , 
   'diagnostics:download'  =>  "Pobierz .txt" , 
   'diagnostics:header'  =>  "========================================================================
Elgg Raport Diagnostyczny
Wygenerowany %s przez %s
========================================================================
			
" , 
   'diagnostics:report:basic'  =>  "Elgg wersja %s, wydanie %s

------------------------------------------------------------------------" , 
   'diagnostics:report:php'  =>  "PHP info:
%s
------------------------------------------------------------------------" , 
   'diagnostics:report:plugins'  =>  "Zainstalowane wtyczki:

%s
------------------------------------------------------------------------" , 
   'diagnostics:report:md5'  =>  "Zainstalowane pliki i suma kontrolna:

%s
------------------------------------------------------------------------" , 
   'diagnostics:report:globals'  =>  "Zmienne globalne:

%s
------------------------------------------------------------------------"
);


add_translation("pl",$polish);



?>